spring:
  profile: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-dummy-for-test}

  datasource:
    postgres:
      url: jdbc:postgresql://115.190.50.51:15432/postgres
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
    mysql:
      url: jdbc:mysql://127.0.0.1:3306/rag_server?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 迁移时是否校验
    validate-on-migrate: false
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:flyway
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql

ai:
  chat:
    model: deepseek-v4-pro
    base-url: https://api.deepseek.com
    api-key: ${DEEPSEEK_API_KEY}
    completionsPath: /chat/completions

  embedding:
    model: text-embedding-v4
    base-url: https://dashscope.aliyuncs.com
    api-key: ${BAILIAN_API_KEY}
    embeddingsPath: /compatible-mode/v1/embeddings
    dimensions: 1024

minio:
  endpoint: http://115.190.50.51:9000
  access-key: a2Eyec0iYiNU80UXThsM
  secret-key: 2GPyC530bZK5DSr6ASOzUCfM317pL9xymd2djf5c
  bucket-name: rag


sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 86400
  active-timeout: -1
  is-log: true
  jwt-secret-key: rag-service-jwt-secret-2026
